import Link from "next/link"
import type { Metadata } from "next";
import "../globals.css";
import { Poppins } from 'next/font/google';
import { Nav, NavLink } from "@/components/NavAdmin";
const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic"


export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
     <html lang="en">
      <body suppressHydrationWarning={true}>
        <Nav>
          <NavLink href="/admin">Dashboard</NavLink>
          <NavLink href="/admin/products">Products</NavLink>
          <NavLink href="/admin/users">Customers</NavLink>
          <NavLink href="/admin/orders">Sales</NavLink>
        </Nav>
        <div className="container my-6 lg:p-24">{children}</div>
      </body>
    </html>
  )
}