import type { Metadata } from "next";
import "../globals.css";
import { Poppins } from 'next/font/google';
import Structure from "@/components/Structure";
import Providers from "@/components/providers/react-queries";
import { SessionProvider } from "next-auth/react";
import { CartProvider } from "@/context/CartContext";

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${poppins.variable} bg-background min-h-screen font-sans antialiased`}>
        <Providers>
        <CartProvider>
          <SessionProvider>
            <Structure>
              {children}
            </Structure>
          </SessionProvider>
        </CartProvider>
        </Providers>
      </body>
    </html>
  );
}
